api_platform:
    title: Narvik - Backend
    version: 0.0.1
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        csv: ['text/csv']
        multipart:
            mime_types: ['multipart/form-data']
    docs_formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
        pagination_client_items_per_page: true
        collection:
            pagination:
                items_per_page_parameter_name: itemsPerPage
    use_symfony_listeners: true
    path_segment_name_generator: api_platform.metadata.path_segment_name_generator.dash
    
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
            Member:
                name: Member
                type: header
