framework:
    rate_limiter:
        # define 2 rate limiters (one for username+IP, the other for IP)
        member_ip_login:
            policy: token_bucket
            limit: 5
            rate: { interval: '5 minutes' }

        ip_login:
            policy: sliding_window
            limit: 50
            interval: '15 minutes'
