# Production environment override
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    environment:
      APP_SECRET: ${APP_SECRET}
      OAUTH_PASSPHRASE: ${OAUTH_PASSPHRASE}
      OAUTH_ENCRYPTION_KEY: ${OAUTH_ENCRYPTION_KEY}

    volumes:
      - app_jwt:/app/config/jwt
      - app_private_files:/app/private
      
  database:
    ports:
      - "5432:5432"

volumes:
  app_jwt:
  app_private_files:
