<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250219161200 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE user_member ALTER id TYPE INT');
        $this->addSql('ALTER TABLE user_member ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE user_security_code ALTER id TYPE INT');
        $this->addSql('ALTER TABLE user_security_code ALTER id DROP IDENTITY');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE user_member ALTER id TYPE INT');
        $this->addSql('ALTER TABLE user_member ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE user_security_code ALTER id TYPE INT');
        $this->addSql('ALTER TABLE user_security_code ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }
}
