App\Entity\ClubDependent\Plugin\Presence\MemberPresence:
    id: ~
    date: ~
    createdAt: ~ 
    
    member:
        prefix: member
        fields:
            id: ~
            licence: ~
            fullName: ~

    activities:
        prefix: activities
        fields:
            id: ~
            name: ~
