App\Entity\ClubDependent\Plugin\Sale\Sale:
    uuid: ~
    createdAt: ~ 
    price: ~ 
    comment: ~ 

    seller:
        prefix: seller
        fields:
            fullName: ~
            licence: ~

    paymentMode:
        prefix: paymentMode
        fields:
            name: ~

    salePurchasedItems:
        prefix: item
        fields:
            itemName: name
            itemCategory: category
            itemPrice: price
            quantity: ~
